### ISSUE TITLE
Arm will not move

### ISSUE THREAD

**Issue by tinyweasel** [mimeindustries/mearm-js#5]
I've installed the image with Etcher on the SD card and it boots fine, I've run the server from the instructions on this page and it runs fine, I've tried to run the code with http://local.headlesspi.org/, but the arm will not move. The screws are loose enough and I don't hear the servos trying to move. I'm positive that it's wired correctly. I'm using a Raspberry Pi B+ with a wired ethernet connection. How can I fix this?

**Comment by tinyweasel** [comment]
Doesn't seem to be communicating with the servos at all.

**Comment by WayneKeenan** [comment]
I have a similar issue.  I've just installed using the instructions in the README to an existing Pi image (CodeAngel, with an rpi-update to latest firmware: 696d7cc2d33acff340fb2ad924d29b9e9f52989d) 

On activating the NodeJS server the status LED lights up and blue/red/ltgreen/dkgreen/off then settles on blue, but there is no servo movement/activity/noise when moving the sticks.  

```bash
pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- 48 -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```

**Comment by tinyweasel** [comment]
Same here in regards to the LED colours.

**Comment by WayneKeenan** [comment]
This servo test code has no effect:

```python
from gpiozero import AngularServo
from time import sleep

for servo_pin in [4, 17, 22, 10]:
    s = AngularServo(servo_pin, min_angle=-45, max_angle=45)
    s.angle = 0.0
    sleep(1)
    s.angle = 15
    sleep(1)
    s.angle = 0
```

**Comment by WayneKeenan** [comment]
ok, for us this turned out to be a power/user issue as the power supply was connected to the Pi and not the MeArm HAT.

**Comment by tinyweasel** [comment]
I tried that but then I couldn't communicate with the Pi. Will try again this evening.

**Comment by WayneKeenan** [comment]
Do you have a beefy (2.1A or more) power supply?

**Comment by tinyweasel** [comment]
I was thinking the current rating might be an issue, the power supply I have is a very cheap one (doesn't have the specs printed on it for some reason even). Will root out a good one this evening and try it out.

**Comment by WayneKeenan** [comment]
Did it work?

**Comment by tinyweasel** [comment]
It didn't, I have it connected to the hat now. One of the servos moved a bit when I pressed a joystick, but now nothing and it's making a weird noise. It stops eventually and drops the arm back down a little. It's not connected to the online thing at the mo as my Pi doesn't have WiFi.

**Comment by tinyweasel** [comment]
Been trying a few different power supplies, looks like it's definitely current related.

**Comment by tinyweasel** [comment]
A 1A power supply and some loosening of screws has the right joystick working but the left is doing nothing.

**Comment by tinyweasel** [comment]
Ahhh, servo cable was wrong was around. We're all good. Thanks for your help!
